// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Orders.Service.Data;

#nullable disable

namespace Orders.Service.Data.Migrations
{
    [DbContext(typeof(OrderDbContext))]
    partial class OrderDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Orders.Service.Entities.InboxMessage", b =>
                {
                    b.Property<Guid>("MessageId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("CorrelationId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("OrderId")
                        .HasColumnType("uuid");

                    b.Property<string>("MessageType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("text");

                    b.Property<string>("Payload")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("ProcessedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamptz")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.HasKey("MessageId");

                    b.HasIndex("CorrelationId")
                        .HasDatabaseName("idx_inbox_correlation_id");

                    b.HasIndex("MessageId")
                        .IsUnique()
                        .HasDatabaseName("idx_inbox_message_id_unique");

                    b.HasIndex("OrderId")
                        .HasDatabaseName("idx_inbox_order_id");

                    b.ToTable("InboxMessages");
                });

            modelBuilder.Entity("Orders.Service.Entities.Order", b =>
                {
                    b.Property<Guid>("OrderId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamptz")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<Guid>("CustomerId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("LastUpdatedAt")
                        .HasColumnType("timestamptz")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<Guid?>("SagaId")
                        .HasColumnType("uuid");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<decimal>("TotalAmount")
                        .HasPrecision(10, 2)
                        .HasColumnType("numeric");

                    b.Property<int>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("integer");

                    b.HasKey("OrderId");

                    b.HasIndex("CreatedAt")
                        .HasDatabaseName("idx_order_created_at");

                    b.HasIndex("CustomerId")
                        .HasDatabaseName("idx_order_customer_id");

                    b.HasIndex("SagaId")
                        .HasDatabaseName("idx_order_saga_id");

                    b.HasIndex("Status")
                        .HasDatabaseName("idx_order_status");

                    b.ToTable("Orders");
                });

            modelBuilder.Entity("Orders.Service.Entities.OrderItem", b =>
                {
                    b.Property<Guid>("OrderItemId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("OrderId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("ProductId")
                        .HasColumnType("uuid");

                    b.Property<decimal>("UnitPrice")
                        .HasPrecision(10, 2)
                        .HasColumnType("numeric");

                    b.Property<int>("Quantity")
                        .HasColumnType("integer");

                    b.HasKey("OrderItemId");

                    b.HasIndex("OrderId")
                        .HasDatabaseName("idx_order_item_order_id");

                    b.ToTable("OrderItems");

                    b.HasCheckConstraint("chk_order_item_quantity_positive", "[Quantity] > 0");
                });

            modelBuilder.Entity("Orders.Service.Entities.OrderStatusTransition", b =>
                {
                    b.Property<Guid>("TransitionId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("CorrelationId")
                        .HasColumnType("uuid");

                    b.Property<string>("FromStatus")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<Guid>("OrderId")
                        .HasColumnType("uuid");

                    b.Property<string>("Reason")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<DateTime>("Timestamp")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamptz")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("ToStatus")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("TransitionId");

                    b.HasIndex("CorrelationId")
                        .HasDatabaseName("idx_transition_correlation_id");

                    b.HasIndex("OrderId")
                        .HasDatabaseName("idx_transition_order_id");

                    b.HasIndex("Timestamp")
                        .HasDatabaseName("idx_transition_timestamp");

                    b.ToTable("OrderStatusTransitions");
                });

            modelBuilder.Entity("Orders.Service.Entities.OrderItem", b =>
                {
                    b.HasOne("Orders.Service.Entities.Order", "Order")
                        .WithMany("Items")
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Order");
                });

            modelBuilder.Entity("Orders.Service.Entities.OrderStatusTransition", b =>
                {
                    b.HasOne("Orders.Service.Entities.Order", "Order")
                        .WithMany("StatusTransitions")
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Order");
                });

            modelBuilder.Entity("Orders.Service.Entities.Order", b =>
                {
                    b.Navigation("Items");

                    b.Navigation("StatusTransitions");
                });
#pragma warning restore 612, 618
        }
    }
}
